# Generated by Django 4.2.6 on 2024-02-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_id',
            name='user',
        ),
        migrations.RemoveField(
            model_name='categoryimages',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Food_Item_Suggestion',
        ),
        migrations.DeleteModel(
            name='PrivacyAndPolicy',
        ),
        migrations.RemoveField(
            model_name='restaurnt_type',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription_features',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Termandcondition',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='count1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='open_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='package',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='payment_diable_enable_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='payment_price',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='restaurant_address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='restaurant_logo',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='service_fee',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscription_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscritpion_expire_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='table_number_status',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='read',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subscriptiondetails',
            name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='subscriptiondetails',
            name='yearly_price',
        ),
        migrations.AddField(
            model_name='customuser',
            name='choose_profilepic',
            field=models.FileField(default='admin/images/user-img.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='notification',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='heading',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='subscription_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiondetails',
            name='subscription_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.customuser'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Account_id',
        ),
        migrations.DeleteModel(
            name='CategoryImages',
        ),
        migrations.DeleteModel(
            name='Restaurnt_type',
        ),
        migrations.DeleteModel(
            name='subscription_features',
        ),
    ]
