# Generated by Django 4.2.6 on 2024-02-26 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Adminapp', '0002_remove_account_id_user_remove_categoryimages_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RestaurentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('restaurant_id', models.CharField(blank=True, max_length=300, null=True, unique=True)),
                ('restaurant_address', models.CharField(blank=True, max_length=3000, null=True)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_code')),
                ('payment_status', models.CharField(default='pending', max_length=200)),
                ('payment_price', models.CharField(default='0', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='FoodName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(blank=True, max_length=200, null=True)),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='food_image')),
                ('full_price', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('medium_price', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('small_price', models.CharField(blank=True, default='-', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='restaurantadminapp.foodcategories')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='foodcategories',
            name='restaurant_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantadminapp.restaurentdetails'),
        ),
        migrations.AddField(
            model_name='foodcategories',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.customuser'),
        ),
    ]
